// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Astro.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Astro_h__
#define __Astro_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Astro
{

class AstroInterface;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Astro::AstroInterface>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Astro::AstroInterface*);

}

}

namespace Astro
{

class AstroInterface;
bool operator==(const AstroInterface&, const AstroInterface&);
bool operator<(const AstroInterface&, const AstroInterface&);
::Ice::Object* upCast(::Astro::AstroInterface*);
typedef ::IceInternal::Handle< ::Astro::AstroInterface> AstroInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Astro::AstroInterface> AstroInterfacePrx;
void __patch(AstroInterfacePtr&, const ::Ice::ObjectPtr&);

}

namespace Astro
{

typedef ::std::vector< ::Ice::Double> agileEvt;

const ::Ice::Int agileEvtSize = 6;

typedef ::std::vector< ::Ice::Double> agileLog;

const ::Ice::Int agileLogSize = 13;

struct AgileEvtKey
{
    ::Ice::Double time;
    ::Ice::Double ra;
    ::Ice::Double dec;
    ::Ice::Double energy;
    ::Ice::Double theta;
    ::Ice::Double evstatus;
};

struct AgileLogKey
{
    ::Ice::Double time;
    ::Ice::Double livetime;
    ::Ice::Double logStatus;
    ::Ice::Double mode;
    ::Ice::Double phase;
};

typedef ::std::vector< ::Ice::Int> SimpleSeq;

typedef ::std::vector< ::Astro::SimpleSeq> Matrix;

typedef ::std::vector< ::Ice::Double> Ra;

typedef ::std::vector< ::Ice::Double> Dec;

typedef ::std::vector< ::Astro::AgileEvtKey> SeqEvtKey;

}

namespace Ice
{
template<>
struct StreamableTraits< ::Astro::AgileEvtKey>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 48;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::Astro::AgileEvtKey, S>
{
    static void write(S* __os, const ::Astro::AgileEvtKey& v)
    {
        __os->write(v.time);
        __os->write(v.ra);
        __os->write(v.dec);
        __os->write(v.energy);
        __os->write(v.theta);
        __os->write(v.evstatus);
    }
};

template<class S>
struct StreamReader< ::Astro::AgileEvtKey, S>
{
    static void read(S* __is, ::Astro::AgileEvtKey& v)
    {
        __is->read(v.time);
        __is->read(v.ra);
        __is->read(v.dec);
        __is->read(v.energy);
        __is->read(v.theta);
        __is->read(v.evstatus);
    }
};

template<>
struct StreamableTraits< ::Astro::AgileLogKey>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 40;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::Astro::AgileLogKey, S>
{
    static void write(S* __os, const ::Astro::AgileLogKey& v)
    {
        __os->write(v.time);
        __os->write(v.livetime);
        __os->write(v.logStatus);
        __os->write(v.mode);
        __os->write(v.phase);
    }
};

template<class S>
struct StreamReader< ::Astro::AgileLogKey, S>
{
    static void read(S* __is, ::Astro::AgileLogKey& v)
    {
        __is->read(v.time);
        __is->read(v.livetime);
        __is->read(v.logStatus);
        __is->read(v.mode);
        __is->read(v.phase);
    }
};

}

namespace Astro
{

class Callback_AstroInterface_calculateMapKey_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AstroInterface_calculateMapKey_Base> Callback_AstroInterface_calculateMapKeyPtr;

class Callback_AstroInterface_calculateMapVector_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AstroInterface_calculateMapVector_Base> Callback_AstroInterface_calculateMapVectorPtr;

class Callback_AstroInterface_shutdown_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AstroInterface_shutdown_Base> Callback_AstroInterface_shutdownPtr;

}

namespace IceProxy
{

namespace Astro
{

class AstroInterface : virtual public ::IceProxy::Ice::Object
{
public:

    ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey& keys)
    {
        return calculateMapKey(keys, 0);
    }
    ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& __ctx)
    {
        return calculateMapKey(keys, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_calculateMapKey(keys, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_calculateMapKey(keys, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_calculateMapKey(keys, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_calculateMapKey(keys, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Astro::Matrix&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
                ::Astro::Matrix __ret;
                try
                {
                    __ret = __proxy->end_calculateMapKey(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Astro::Matrix&)> _response;
        };
        return begin_calculateMapKey(keys, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys)
    {
        return begin_calculateMapKey(keys, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& __ctx)
    {
        return begin_calculateMapKey(keys, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapKey(keys, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapKey(keys, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Astro::Callback_AstroInterface_calculateMapKeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapKey(keys, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey& keys, const ::Ice::Context& __ctx, const ::Astro::Callback_AstroInterface_calculateMapKeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapKey(keys, &__ctx, __del, __cookie);
    }

    ::Astro::Matrix end_calculateMapKey(const ::Ice::AsyncResultPtr&);
    
private:

    ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Astro::Matrix calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector)
    {
        return calculateMapVector(raVector, decVector, 0);
    }
    ::Astro::Matrix calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& __ctx)
    {
        return calculateMapVector(raVector, decVector, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_calculateMapVector(raVector, decVector, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_calculateMapVector(raVector, decVector, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_calculateMapVector(raVector, decVector, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_calculateMapVector(raVector, decVector, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::Astro::Matrix&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Astro::Matrix&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
                ::Astro::Matrix __ret;
                try
                {
                    __ret = __proxy->end_calculateMapVector(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Astro::Matrix&)> _response;
        };
        return begin_calculateMapVector(raVector, decVector, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector)
    {
        return begin_calculateMapVector(raVector, decVector, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& __ctx)
    {
        return begin_calculateMapVector(raVector, decVector, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapVector(raVector, decVector, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapVector(raVector, decVector, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Astro::Callback_AstroInterface_calculateMapVectorPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapVector(raVector, decVector, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra& raVector, const ::Astro::Dec& decVector, const ::Ice::Context& __ctx, const ::Astro::Callback_AstroInterface_calculateMapVectorPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_calculateMapVector(raVector, decVector, &__ctx, __del, __cookie);
    }

    ::Astro::Matrix end_calculateMapVector(const ::Ice::AsyncResultPtr&);
    
private:

    ::Astro::Matrix calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void shutdown()
    {
        shutdown(0);
    }
    void shutdown(const ::Ice::Context& __ctx)
    {
        shutdown(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(&ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(&ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_shutdown()
    {
        return begin_shutdown(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx)
    {
        return begin_shutdown(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Astro::Callback_AstroInterface_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Astro::Callback_AstroInterface_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    void end_shutdown(const ::Ice::AsyncResultPtr&);
    
private:

    void shutdown(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_secure(bool __secure) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_twoway() const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_oneway() const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_batchOneway() const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_datagram() const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_batchDatagram() const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_compress(bool __compress) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_timeout(int __timeout) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AstroInterface> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<AstroInterface*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Astro
{

class AstroInterface : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Astro::Matrix calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Astro
{

class AstroInterface : virtual public ::IceDelegate::Astro::AstroInterface,
                       virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Astro::Matrix calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Astro
{

class AstroInterface : virtual public ::IceDelegate::Astro::AstroInterface,
                       virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Astro::Matrix calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Astro
{

class AstroInterface : virtual public ::Ice::Object
{
public:

    typedef AstroInterfacePrx ProxyType;
    typedef AstroInterfacePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Astro::Matrix calculateMapKey(const ::Astro::SeqEvtKey&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___calculateMapKey(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Astro::Matrix calculateMapVector(const ::Astro::Ra&, const ::Astro::Dec&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___calculateMapVector(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void shutdown(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___shutdown(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const AstroInterface& l, const AstroInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const AstroInterface& l, const AstroInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Astro
{

template<class T>
class CallbackNC_AstroInterface_calculateMapKey : public Callback_AstroInterface_calculateMapKey_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Astro::Matrix&);

    CallbackNC_AstroInterface_calculateMapKey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
        ::Astro::Matrix __ret;
        try
        {
            __ret = __proxy->end_calculateMapKey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_AstroInterface_calculateMapKeyPtr
newCallback_AstroInterface_calculateMapKey(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Astro::Matrix&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_calculateMapKey<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AstroInterface_calculateMapKeyPtr
newCallback_AstroInterface_calculateMapKey(T* instance, void (T::*cb)(const ::Astro::Matrix&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_calculateMapKey<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_AstroInterface_calculateMapKey : public Callback_AstroInterface_calculateMapKey_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Astro::Matrix&, const CT&);

    Callback_AstroInterface_calculateMapKey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
        ::Astro::Matrix __ret;
        try
        {
            __ret = __proxy->end_calculateMapKey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_AstroInterface_calculateMapKeyPtr
newCallback_AstroInterface_calculateMapKey(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Astro::Matrix&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_calculateMapKey<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AstroInterface_calculateMapKeyPtr
newCallback_AstroInterface_calculateMapKey(T* instance, void (T::*cb)(const ::Astro::Matrix&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_calculateMapKey<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_AstroInterface_calculateMapVector : public Callback_AstroInterface_calculateMapVector_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Astro::Matrix&);

    CallbackNC_AstroInterface_calculateMapVector(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
        ::Astro::Matrix __ret;
        try
        {
            __ret = __proxy->end_calculateMapVector(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_AstroInterface_calculateMapVectorPtr
newCallback_AstroInterface_calculateMapVector(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Astro::Matrix&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_calculateMapVector<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AstroInterface_calculateMapVectorPtr
newCallback_AstroInterface_calculateMapVector(T* instance, void (T::*cb)(const ::Astro::Matrix&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_calculateMapVector<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_AstroInterface_calculateMapVector : public Callback_AstroInterface_calculateMapVector_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Astro::Matrix&, const CT&);

    Callback_AstroInterface_calculateMapVector(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Astro::AstroInterfacePrx __proxy = ::Astro::AstroInterfacePrx::uncheckedCast(__result->getProxy());
        ::Astro::Matrix __ret;
        try
        {
            __ret = __proxy->end_calculateMapVector(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_AstroInterface_calculateMapVectorPtr
newCallback_AstroInterface_calculateMapVector(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Astro::Matrix&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_calculateMapVector<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AstroInterface_calculateMapVectorPtr
newCallback_AstroInterface_calculateMapVector(T* instance, void (T::*cb)(const ::Astro::Matrix&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_calculateMapVector<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_AstroInterface_shutdown : public Callback_AstroInterface_shutdown_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AstroInterface_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AstroInterface_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AstroInterface_shutdown : public Callback_AstroInterface_shutdown_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AstroInterface_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_shutdown<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AstroInterface_shutdownPtr
newCallback_AstroInterface_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AstroInterface_shutdown<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
